version: 2.1

commands:
  tester:
    description: "Test plotille given a certain python version."
    steps:
      - checkout
      
      - run:
          name: Set PATH.
          command: |
            echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Pre-install
          command: |
            pip install --user poetry virtualenv
            virtualenv venv

      - run:
          name: Install
          command: |
            . venv/bin/activate
            poetry install
            poetry show --tree

      - run:
          name: Test
          command: |
            . venv/bin/activate
            poetry run pytest

      - run:
          name: Coverage
          command: |
            . venv/bin/activate
            poetry run coveralls

jobs:
  test_2_7:
    docker:
      - image: circleci/python:2.7.15
    steps:
      - tester
  test_2_7_pypy:
    docker:
      - image: pypy:2-6.0.0
    steps:
      - tester
  test_3_5:
    docker:
      - image: circleci/python:3.5.6
    steps:
      - tester
  test_3_5_pypy:
    docker:
      - image: pypy:3-6.0.0
    steps:
      - tester
  test_3_6:
    docker:
      - image: circleci/python:3.6.7
    steps:
      - tester
  test_3_7:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - tester
  
  deploy_job:
    docker:
      - image: circleci/python:3.6.7
    description: "Deploy plotille to pypi."
    steps:
      - checkout
      
      - run:
          name: Set PATH.
          command: |
            echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Pre-install
          command: |
            pip install --user poetry
            poetry build -f sdist
            echo "poetry publish -u tammoippen -p <pass>"

workflows:
  version: 2.1
  test_and_deploy:
    jobs:
      - test_2_7
      - test_2_7_pypy
      - test_3_5
      - test_3_5_pypy
      - test_3_6
      - test_3_7
      - deploy_job:
          requires:
            - test_2_7
            - test_2_7_pypy
            - test_3_5
            - test_3_5_pypy
            - test_3_6
            - test_3_7
          filters:
            # branches:
            #   only: master
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
