version: 2.1

commands:
  tester:
    description: "Test plotille given a certain python version."
    steps:
      - checkout
      
      - run: 
        command: |
          pip install poetry virtualenv
          python -m virtualenv venv
      
      - run:
        command: |
          poetry install
          poetry show
          
      - run: 
        command: poetry run pytest
      
      - run: 
        command: coveralls

jobs:
  test_2_7:
    docker:
      - image:  circleci/python:2.7.15
    steps:
      - tester
  test_2_7_pypy:
    docker:
      - image:  pypy:2-6.0.0
    steps:
      - tester
  test_3_5:
    docker:
      - image:  circleci/python:3.5.6
    steps:
      - tester
  test_3_5_pypy:
    docker:
      - image:  pypy:3-6.0.0
    steps:
      - tester
  test_3_6:
    docker:
      - image:  circleci/python:3.6.7
    steps:
      - tester
  test_3_7:
    docker:
      - image:  circleci/python:3.7.1
    steps:
      - tester
      
workflows:
  version: 2.1
  test_and_deploy:
    jobs:
      - test_2_7
      - test_2_7_pypy
      - test_3_5
      - test_3_5_pypy
      - test_3_6
      - test_3_7
